"""Generate includes/telemetry-sensors.md: the telemetry sensor ID table.

Sensor IDs come from src/main/telemetry/sensors.h, the S.Port and CRSF IDs
from the TLM_SENSOR tables in smartport.c and crsf.c, and the display names
from the Configurator's English locale.

Usage:
    python tools/gen_telemetry_sensors.py <rotorflight-firmware> <rotorflight-configurator> [fw ref] [cfg ref]
"""
import json
import os
import re
import subprocess
import sys

fw, cfg = sys.argv[1], sys.argv[2]
fw_ref = sys.argv[3] if len(sys.argv) > 3 else "upstream/master"
cfg_ref = sys.argv[4] if len(sys.argv) > 4 else "upstream/master"
out = os.path.join(os.path.dirname(__file__), "..", "includes", "telemetry-sensors.md")


def show(repo, ref, path):
    return subprocess.run(["git", "-C", repo, "show", f"{ref}:{path}"],
                          capture_output=True, text=True, encoding="utf-8", check=True).stdout


sensors = re.findall(r"TELEM_([A-Z0-9_]+)\s*=\s*(\d+)", show(fw, fw_ref, "src/main/telemetry/sensors.h"))


def ids(path):
    return dict(re.findall(r"TLM_SENSOR\(\s*([A-Z0-9_]+)\s*,\s*(0x[0-9A-Fa-f]+)", show(fw, fw_ref, path)))


sport = ids("src/main/telemetry/smartport.c")
crsf = ids("src/main/telemetry/crsf.c")
msgs = json.loads(show(cfg, cfg_ref, "locales/en/messages.json"))

lines = ["| ID | Sensor | Configurator name | S.Port ID | CRSF custom ID |",
         "| --: | --- | --- | --- | --- |"]
for name, num in sensors:
    if name in ("NONE", "SENSOR_COUNT"):
        continue
    # Same rule as the Configurator's sensor list: ESC1_X shows as "#1 <ESC_X label>".
    esc = re.match(r"ESC(\d)_", name)
    key = re.sub(r"^ESC\d", "ESC", name) if esc else name
    label = msgs.get(f"receiverTelemetrySensor_{key}", {}).get("message", "")
    label = re.sub(r"<[^>]+>", "", label)
    if esc and label:
        label = f"#{esc.group(1)} {label}"
    sp = f"`{sport[name]}`" if name in sport else ""
    cr = f"`{crsf[name]}`" if name in crsf else ""
    lines.append(f"| {num} | `{name}` | {label} | {sp} | {cr} |")

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("<!-- Generated by tools/gen_telemetry_sensors.py. Do not edit by hand. -->\n\n")
    f.write("\n".join(lines) + "\n")
print(f"wrote {len(lines) - 2} sensors to {os.path.normpath(out)}")
